name: Build
on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PUBLIC_BASEURL: ${{ secrets.PUBLIC_BASEURL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_OAUTH_ID: ${{ secrets.GOOGLE_OAUTH_ID }}
      GOOGLE_OAUTH_SECRET: ${{ secrets.GOOGLE_OAUTH_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Check
        run: npm run check

      - name: Build
        run: npm run build
